= bookproject

Trivial application to retrieve bibliographic information from providers

== Spring Boot

=== Build and Run

.Build
 $ ./gradlew -q clean build

.Run boot app from gradle
 $ ./gradlew -q bootRun

.Debug boot app from gradle
 $ ./gradlew -q bootRun -Pdebug

then attach debugger to port 8000.

.Build war and run
 $ ./gradlew -q clean bootWar
 $ java -jar build/libs/scraper-0.0.1-boot.war

NOTE: To skip the tests pass `-x test` to gradle

=== Use

.Basic UI
 http://localhost:8080/

.Invoke the REST API
 http://localhost:8080/search?isbn=9789600316698

.Application information
 http://localhost:8080/actuator/info

NOTE: Provided through the actuator module

== Database
The application uses the H2 database at its persistence layer. Before starting the application an H2 database in server mode must be running.

.Start H2
 $ java -cp h2.jar org.h2.tools.Server

== Deploy on Tomcat
The bundled application can be deployed on a Tomcat, through the cargo plugin:

 $ ./gradlew clean war cargoReDeployRemote

NOTE: Obviously, tomcat must be up and running. The same is true for an H2 database. Tomcat deployer configuration is in the root `build.gradle`.

== Reports

 $ ./gradlew -q allReports

NOTE: Custom task using the _build-dashboard_ plugin.

Report available on `build\reports\buildDashboard\index.html`.
